[package]
name = "telora-common"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
dirs = "5"
log = "0.4"
nix = { version = "0.27", features = ["fs", "user", "socket"] }
tokio = { version = "1.36", features = ["net"] }
socket2 = "0.5"

[target.'cfg(target_os = "linux")'.dependencies]
libsystemd = { workspace = true }

[dev-dependencies]
tempfile = "3"
tokio = { version = "1.36", features = ["full", "test-util"] }
